apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-eta-deploy
  labels:
    app: bankapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-eta-app
  template:
    metadata:
      labels:
        app: bankapp-eta-app
    spec:
      containers:
      - name: bankapp-eta-container
        image: loksaieta/bankapp-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-np-service
  labels:
    app: bankapp-eta-app
spec:
  selector:
    app: bankapp-eta-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082

    ---

    apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

